stages: [ test, plan, deploy ]

include:
- component: $CI_SERVER_FQDN/util/k8s-ci/kustomize@0.3.1
  inputs:
    prune: [ core/v1/Secret, core/v1/ConfigMap,
             apps/v1/StatefulSet, apps/v1/Deployment,
             batch/v1/CronJob,
             core/v1/Service, networking.k8s.io/v1/Ingress,
             networking.k8s.io/v1/NetworkPolicy ]
    envsubst: [ DIZ_NAME ]
- component: ${CI_SERVER_FQDN}/util/terraform-component/validate@main
  inputs:
    stage: test
- component: ${CI_SERVER_FQDN}/util/terraform-component/plan@main
  inputs:
    stage: plan

# DIZ names, also consumed by terraform
.dizs: &dizs
- test-1

.tf/init:
  variables:
    TF_VAR_password_seed: "${PASSWORD_SEED}"

.app/apply:
  before_script:
  - kustomize edit add secret credentials
    --from-literal=$(./genpassenv.sh CD_HDS_BACKEND_AUTH_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh CD_HDS_FRONTEND_AUTH_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh CD_HDS_FRONTEND_AUTH_SECRET)
    --from-literal=$(./genpassenv.sh RD_HDS_BACKEND_AUTH_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh RD_HDS_FRONTEND_AUTH_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh RD_HDS_FRONTEND_AUTH_SECRET)
    --from-literal=$(./genpassenv.sh CD_FTS_AGENT_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh CD_FTS_TC_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh RD_FTS_AGENT_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh RD_FTS_TC_CLIENT_SECRET)
    --from-literal=$(./genpassenv.sh FTS_SCHEDULER_CLIENT_SECRET)

# Validate with a fixed placeholder so the job doesn't need real DIZ credentials.
app/validate:
  variables:
    DIZ_NAME: test-1

app/deploy:test:
  rules:
  - when: never

app/deploy:prod:
  parallel:
    matrix:
    - DIZ_NAME: *dizs
  environment:
    # We use a fixed KUBE_CLUSTER from CI/CD variables,
    # so we can use the DIZ name as the environment
    name: $DIZ_NAME
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  - if: $CI_MERGE_REQUEST_LABELS =~ /hint::autodeploy/
  - when: manual
