apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distance-xt-${DIZ_NAME}

labels:
- pairs:
    app.kubernetes.io/part-of: distance-xt-diz

resources:
- rp/
- cd/
- rd/
- fdpg/
- netpol.yaml
