#!/bin/sh
# Register all required Kustomize secrets from extracted credentials and
# generated passwords.
set -eu

mkdir -p ./.secrets

BASE_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 || exit 1 ; pwd -P )"

envFile="${1:?Usage: $0 <env-file>}"

secrets="
CD_HDS_BACKEND_AUTH_CLIENT_SECRET
CD_HDS_FRONTEND_AUTH_CLIENT_SECRET
CD_HDS_FRONTEND_AUTH_SECRET
RD_HDS_BACKEND_AUTH_CLIENT_SECRET
RD_HDS_FRONTEND_AUTH_CLIENT_SECRET
RD_HDS_FRONTEND_AUTH_SECRET
CD_FTS_AGENT_CLIENT_SECRET
CD_FTS_TC_CLIENT_SECRET
RD_FTS_AGENT_CLIENT_SECRET
RD_FTS_TC_CLIENT_SECRET
FTS_SCHEDULER_CLIENT_SECRET
FDPG_DSF_BPE_DB_LIQUIBASE_PASSWORD
FDPG_DSF_BPE_DB_USER_ENGINE_PASSWORD
FDPG_DSF_BPE_DB_USER_PASSWORD
FDPG_DSF_BPE_RD_HDS_CLIENT_SECRET
FDPG_DSF_MAILBOX_AUTH_CLIENT_SECRET
FDPG_DSF_MAILBOX_DB_LIQUIBASE_PASSWORD
FDPG_DSF_MAILBOX_DB_USER_PASSWORD
FDPG_DSF_MAILBOX_DB_USER_PERMANENT_DELETE_PASSWORD
FDPG_PRIVATE_KEY_PASSWORD
RP_DSF_MAILBOX_AUTH_CLIENT_SECRET
RP_DSF_MAILBOX_DB_LIQUIBASE_PASSWORD
RP_DSF_MAILBOX_DB_USER_PASSWORD
RP_DSF_MAILBOX_DB_USER_PERMANENT_DELETE_PASSWORD
RP_PRIVATE_KEY_PASSWORD
"

for secret in $secrets
do
  "${BASE_DIR}/genpassenv.sh" $secret >> "$envFile"
done

